# Generated by Django 3.2 on 2021-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='weight_in_gram',
        ),
        migrations.AddField(
            model_name='parcel',
            name='weight',
            field=models.FloatField(default=500),
        ),
    ]
