# Generated by Django 3.0.7 on 2021-04-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_districts_divisions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districts',
            old_name='divisionId',
            new_name='division',
        ),
    ]
