# Generated by Django 3.2 on 2021-05-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parcel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
