# Generated by Django 3.2 on 2021-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parcel_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='return_chagre',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
