# Generated by Django 3.2 on 2021-05-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parcel_return_chagre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='return_chagre',
            new_name='return_charge',
        ),
    ]
